// <auto-generated>
// Rewired Constants
// This list was generated on 8/31/2021 5:01:45 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Start")]
        public const int Start = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Select")]
        public const int Select = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Back")]
        public const int Back = 6;
        // Ball
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ball", friendlyName = "Move Horizontal")]
        public const int MoveHorizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ball", friendlyName = "Move Vertical")]
        public const int MoveVertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ball", friendlyName = "Jump")]
        public const int Jump = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ball", friendlyName = "Look Horizontal")]
        public const int LookHorizontal = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ball", friendlyName = "Look Vertical")]
        public const int LookVertical = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Ball", friendlyName = "Dampen")]
        public const int Dampen = 9;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int Ball = 1;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
